run:
	@go run ./cmd

run1:
	@go run ./cmd --part1

run2:
	@go run ./cmd --part2

debug1:
	@go run ./cmd --part1 --debug

debug2:
	@go run ./cmd --part2 --debug

test:
	@go test ./p1
	@go test ./p2

test1:
	@go test ./p1

test2:
	@go test -count=1 ./p2

build:
	@go build -o ./bin/aoc

clean:
	@rm -r ./bin
